# Generated by Django 5.1.1 on 2024-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_stack_name'),
        ('users', '0003_alter_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='prog_language',
        ),
        migrations.AddField(
            model_name='customuser',
            name='prog_language',
            field=models.ManyToManyField(blank=True, to='skills.proglanguage'),
        ),
    ]
