# Generated by Django 5.1.1 on 2024-10-04 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_prog_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res-console.cloudinary.com/dwzqcmaod/thumbnails/v1/image/upload/v1728056035/YXZhdGFyLXJlbW92ZWJnLXByZXZpZXdfb3J5Ympz/preview', max_length=255, null=True, verbose_name='image'),
        ),
    ]
