# Generated by Django 5.1.1 on 2024-10-04 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dwzqcmaod/image/upload/w_1000,c_fill,ar_1:1,g_auto,r_max,bo_5px_solid_red,b_rgb:262c35/v1728056035/avatar-removebg-preview_orybjs.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
