# Generated by Django 5.1.1 on 2024-10-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='skills.proglanguage'),
        ),
        migrations.AddField(
            model_name='project',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.level'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.stack'),
        ),
        migrations.AddField(
            model_name='session',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='languages',
            field=models.ManyToManyField(blank=True, to='skills.proglanguage'),
        ),
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.level'),
        ),
        migrations.AddField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='sessions_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='session',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.stack'),
        ),
        migrations.AddField(
            model_name='interestedparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.session'),
        ),
    ]
