# Generated by Django 5.1.1 on 2024-09-26 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_language_session_prog_language_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.stack'),
        ),
    ]
