# Generated by Django 5.1.1 on 2024-09-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_stack'),
        ('skills', '0003_alter_stack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.stack'),
        ),
    ]
