# Generated by Django 5.1.1 on 2024-09-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_session_prog_language_session_prog_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='prog_language',
            new_name='languages',
        ),
    ]
