# Generated by Django 5.1.1 on 2024-10-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_active_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Default Session Name', max_length=255),
        ),
    ]
