# Generated by Django 5.1.1 on 2024-10-04 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_active_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res-console.cloudinary.com/dwzqcmaod/thumbnails/v1/image/upload/v1728056127/Y29kZV9hZGtnb3k=/preview', max_length=255, null=True, verbose_name='image'),
        ),
    ]
