# Generated by Django 5.1.1 on 2024-10-04 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dwzqcmaod/image/upload/v1728056127/code_adkgoy.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
