# Generated by Django 5.1.1 on 2024-10-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_session_description'),
        ('projects', '0013_session_name_alter_project_image'),
    ]

    operations = [
    ]
