# Generated by Django 5.1.1 on 2024-09-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20240926_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='name',
            field=models.CharField(choices=[('Fullstack', 'Fullstack'), ('Backend', 'Backend'), ('Frontend', 'Frontend')], max_length=100, unique=True),
        ),
    ]
